name: "Test Backend Extension"
on: [push, pull_request]

jobs:
  test:
    name: Test backend extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./publishjgivenreport
        run: npm install
      - name: Run tests
        working-directory: ./publishjgivenreport
        run: npm test